import React from 'react';
import { Download, FileJson, FileSpreadsheet, ShieldCheck } from 'lucide-react';

export const ReportsView: React.FC = () => {
  const handleDownload = (format: string) => {
    window.open(`/api/v1/export/${format}`, '_blank');
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
      {/* Header */}
      <div className="glass-panel" style={{ padding: '20px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <span className="badge badge-cyan">AUDIT & EXPORT</span>
              <span className="badge badge-muted">AUTOMOTIVE COMPLIANCE PACKAGE</span>
            </div>
            <h2 style={{ fontSize: '20px', fontWeight: 700, color: '#ffffff' }}>
              Engineering Verification Reports & Test Suite Export
            </h2>
            <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginTop: '4px' }}>
              Generate complete traceability matrices, simulation test execution logs, and specification gap reports.
            </p>
          </div>
        </div>
      </div>

      {/* Export Action Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px' }}>
        <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
              <FileJson size={24} color="var(--accent-cyan)" />
              <h3 style={{ fontSize: '17px', fontWeight: 600 }}>Structured JSON Test Package</h3>
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '13px', lineHeight: 1.5 }}>
              Export complete test specifications, input signal vectors, multi-ECU dependency arrays, 
              and deterministic simulation logs formatted for automated CI/HIL ingestion.
            </p>
          </div>
          <button className="btn-primary" onClick={() => handleDownload('json')}>
            <Download size={15} /> Download Full Test Suite (JSON)
          </button>
        </div>

        <div className="glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
              <FileSpreadsheet size={24} color="var(--status-pass)" />
              <h3 style={{ fontSize: '17px', fontWeight: 600 }}>Spreadsheet Traceability Matrix</h3>
            </div>
            <p style={{ color: 'var(--text-muted)', fontSize: '13px', lineHeight: 1.5 }}>
              Tabular spreadsheet containing Requirement-to-Test mapping, status, blocked reasons, 
              and flagged specification gaps for engineering management review.
            </p>
          </div>
          <button className="btn-secondary" onClick={() => handleDownload('csv')}>
            <Download size={15} /> Download CSV Matrix
          </button>
        </div>
      </div>

      {/* Compliance & Engineering Sign-Off Notice */}
      <div className="glass-panel" style={{ padding: '20px', borderLeft: '4px solid #60a5fa' }}>
        <h4 style={{ fontSize: '14px', fontWeight: 600, color: '#ffffff', marginBottom: '6px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <ShieldCheck size={18} color="#60a5fa" /> Engineering Approval & Legal Notice
        </h4>
        <p style={{ color: 'var(--text-muted)', fontSize: '13px', lineHeight: 1.5 }}>
          All AI-synthesized test specifications generated by CIVIC-AI represent automated verification proposals 
          and require formal sign-off by a qualified automotive systems safety engineer before release to production HIL rigs. 
          The fictional reference vehicle PUSV-01 is an open architecture inspired by publicly documented compact sedan capabilities 
          and contains zero proprietary OEM code.
        </p>
      </div>
    </div>
  );
};
